GET http://localhost:3005/users

###

# ---- SQL Injection Exploit ----
# ⚠️ We never, Ever directly concatenate user-provided input
# into SQL query
# 💡 Add code to 'sanitize' user provided values to our app
# 💡 Or rely on Postgres to sanitize values for us
# GET http://localhost:3005/users/1;DROP TABLE users;


GET http://localhost:3005/users/1

###

POST http://localhost:3005/users
Content-Type: application/json

{
  "username": "minty3",
  "bio": "I am a mint"
}

###

PUT http://localhost:3005/users/1
Content-Type: application/json

{
  "username": "Alyson156",
  "bio": "I am a alyson"
}